CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  email TEXT NOT NULL UNIQUE,
  password CHAR(60) NOT NULL
);

CREATE TABLE tasks (
  id SERIAL PRIMARY KEY,
  users_id INTEGER NOT NULL,
  text VARCHAR(200) NOT NULL,
  completed BOOLEAN DEFAULT FALSE,
  date DATE NOT NULL
);

CREATE TABLE sub_list_items (
  id SERIAL PRIMARY KEY,
  tasks_id INTEGER NOT NULL,
  users_id INTEGER NOT NULL,
  text VARCHAR(200) NOT NULL,
  completed BOOLEAN DEFAULT FALSE
);
